name: Test

on:
  push:
  pull_request:

jobs:
  build:
    name: Testing
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        scala: [2.13.2, 2.12.11]
        java: [adopt@1.8]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Ignore line ending differences in git
        if: contains(runner.os, 'windows')
        shell: bash
        run: git config --global core.autocrlf false

      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}

      - name: Run tests
        run: sbt coverage test
        shell: bash

      - name: Coverage Report
        if: contains(runner.os, 'linux')
        run: sbt coverageReport
        shell: bash

      - name: Upload coverage to Codecov
        if: contains(runner.os, 'linux')
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
